### ISSUE TITLE
Beacons Not Working Right with AI Vehicle Extension Mod

### ISSUE THREAD

**Issue by therealcrow999** [TyKonKet/FS17_CombineSignals#3]
If I use the AI from AI Vehicle Extension mod, the Beacons won't signal right or not at all. I can use the AI from FS17 website or use 1.0.0.8 from GitHub and still has issues. 
https://github.com/Mogli12/AIVehicleExtension

Combine Signal mod works fine if I don't use AI Vehicle Extension mod, if in game I select to use default AI with the mod. 

The sound and audio seem to be going off fine.

Thanks.

**Comment by TyKonKet** [comment]
Ask a fix to creator of "AIVehicleExtension", I think his mod overwrites some of my functions.

**Comment by therealcrow999** [comment]
Thanks, I sent one over after I wrote this up here. I wasn't to sure which mod it was.
